### ISSUE TITLE
Request for Enhancement: Support for team_number() intrinsic function

### ISSUE THREAD

**Issue by rouson** [sourceryinstitute/gcc#1]
Section 16.9.189 of Committee Draft 1539-1  of the Fortran 2015 standard describes a `team_number` intrinsic function which takes an optional scalar argument of type `team_type`  "whose value identifies the current or an ancestor team."  The result is a default integer scalar and "has the value −1 if the speci ed team is the initial team; otherwise, the result value is equal to the positive integer that identifies the specified team within its parent team." If the optional argument is absent, then the current team specified. 

@afanfa I can take a stab at writing the library side.  Could you write the compiler side?

**Comment by rouson** [comment]
@afanfa FYI, I have a draft of the library implementation of `team_number` now and am writing unit tests for it now.

**Comment by rouson** [comment]
@scrasmussen  If you're interested and available in working on the compiler support for `team_number`, let me know.  The above referenced draft of the Fortran standard is [here](https://bit.ly/fortran-2015-draft).  It's dated July 6, 2017.  If you decide to work on this, make sure you're looking at this draft because there were some recent changes to the teams feature.  They probably don't affect `team_number` though.

**Comment by scrasmussen** [comment]
@rouson I'd be interested to work on compiler support but the amount of time I can put towards it might be limited right now. What is the timeline that you'd like to see this completed? I can take a closer look at this on Sunday.

**Comment by rouson** [comment]
@scrasmussen My guess is this is only a few minutes of work for @afanfa , but he's away in a course this week and returning to the office next week.  If you do take a look before Monday and think it's something you'd like to work on, let us know.  Otherwise, I'll check whether Alessandro has the time to work on this next week.

**Comment by scrasmussen** [comment]
@rouson if it's only a few minutes of work for @afanfa it seems like a perfect thing to help me get familiar with the project! I know it will take me a lot lot longer but I'll start looking at it.
